global:
  # How long to wait before sending a notification about a firing alert
  resolve_timeout: 5m

route:
  # Default receiver if no other route matches
  receiver: email

  # Send all alerts to all receivers (for simplicity)
  routes:
    - receiver: email
    - receiver: slack

receivers:
  # Email notifications
  - name: email
    email_configs:
      - to: ${TO_EMAIL}
        from: ${FROM_EMAIL}
        smarthost: ${SMTP_HOST}:${SMTP_PORT}
        auth_username: ${AUTH_USERNAME}
        auth_identity: ${AUTH_IDENTITY}
        auth_password: ${SMTP_PASSWORD}
        require_tls: true

  # Slack notifications
  - name: slack
    slack_configs:
      - api_url: https://$SLACK_API_URL
        channel: ${SLACK_CHANNEL}
        send_resolved: true
        text: |-
          *Alert:* {{ .CommonAnnotations.summary }}
          *Description:* {{ .CommonAnnotations.description }}
          *Severity:* {{ .CommonLabels.severity }}
          *Instance:* {{ .CommonLabels.instance }}
