global:
  # How long to wait before sending a notification about a firing alert
  resolve_timeout: 5m

route:
  # Default receiver if no other route matches
  receiver: email

  # Send all alerts to all receivers (for simplicity)
  routes:
    - receiver: email
    - receiver: slack

receivers:
  # Email notifications
  - name: email
    email_configs:
      - to: ${TO_EMAIL}  # Recipient email address
        from: ${FROM_EMAIL}  # Sender email address
        smarthost: ${SMARTHOST}  # SMTP server address (e.g., smtp.gmail.com:587)
        auth_username: ${AUTH_USERNAME}  # SMTP authentication username
        auth_identity: ${AUTH_IDENTITY}  # SMTP authentication identity (usually same as username)
        auth_password: ${SMTP_PASSWORD}  # SMTP authentication password
        require_tls: true

  # Slack notifications
  - name: slack
    slack_configs:
      - api_url: ${SLACK_API_URL}  # Slack webhook URL for notifications
        channel: ${SLACK_CHANNEL}  # Slack channel name (e.g., #alerts)
        send_resolved: true
        text: |-
          *Alert:* {{ .CommonAnnotations.summary }}
          *Description:* {{ .CommonAnnotations.description }}
          *Severity:* {{ .CommonLabels.severity }}
          *Instance:* {{ .CommonLabels.instance }}
