global:
  # How long to wait before sending a notification about a firing alert
  resolve_timeout: 5m

route:
  # Default receiver if no other route matches
  receiver: email

  # Send all alerts to all receivers (for simplicity)
  routes:
    - receiver: email
    - receiver: slack

receivers:
  # Email notifications
  - name: email
    email_configs:
      - to: "your-email@example.com"  # Recipient email address
        from: "alertmanager@example.com"  # Sender email address
        smarthost: "smtp.gmail.com:587"  # SMTP server address, only change this if you have something else
        auth_username: "your-gmail@gmail.com"  # SMTP authentication username
        auth_identity: "your-gmail@gmail.com"  # SMTP authentication identity (usually same as username)
        auth_password: "your password here"  # Use Gmail app password, not your main password
        require_tls: true

  # Slack notifications
  - name: slack
    slack_configs:
      - api_url: "https://hooks.slack.com/services/T00000000/B00000000/XXXXXXXXXXXXXXXXXXXXXXXX"  # Slack webhook URL for notifications
        channel: "#alerts"  # Slack channel name (e.g., #alerts)
        send_resolved: true
        text: |-
          *Alert:* {{ .CommonAnnotations.summary }}
          *Description:* {{ .CommonAnnotations.description }}
          *Severity:* {{ .CommonLabels.severity }}
          *Instance:* {{ .CommonLabels.instance }}
