name: CI - Monitoring Stack

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Validate Docker Compose config
        run: docker compose config

      - name: Validate Prometheus config
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/prometheus:/etc/prometheus:ro" \
            --entrypoint /bin/promtool \
            prom/prometheus:v2.53.5 \
            check config /etc/prometheus/prometheus.yml

      - name: Validate Alertmanager config
        run: |
          docker run --rm \
            -v "${{ github.workspace }}/prometheus/alertmanager.yml:/etc/alertmanager/alertmanager.yml:ro" \
            --entrypoint /bin/amtool \
            prom/alertmanager:v0.28.1 \
            check-config /etc/alertmanager/alertmanager.yml

  smoke-test:
    runs-on: ubuntu-latest
    needs: validate
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker
        uses: docker/setup-buildx-action@v3

      - name: Start stack
        run: docker compose up -d --build

      - name: Wait for services to start
        run: sleep 30

      - name: Check container health
        run: |
          unhealthy=$(docker inspect --format '{{.Name}} {{.State.Health.Status}}' $(docker ps -q) | grep -v healthy || true)
          if [ -n "$unhealthy" ]; then
            echo "Unhealthy containers found:"
            echo "$unhealthy"
            exit 1
          fi

      - name: Tear down stack
        run: docker compose down
